create database lionfart;

use lionfart;

create user 'lionfart' IDENTIFIED BY 'YOUR PASSWORD GOES HERE';

GRANT ALL PRIVILEGES ON lionfart.* TO 'lionfart';

CREATE TABLE `role` (
  `ROLE_ID` int(10) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(70) NOT NULL,
  `CREATED_BY` varchar(45) NOT NULL,
  `CREATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(45) DEFAULT NULL,
  `MODIFIED_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ROLE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE `user` (
  `USER_ID` int(10) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(70) NOT NULL,
  `PASSWORD` varchar(64) NOT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `FIRST_NAME` varchar(70) DEFAULT NULL,
  `LAST_NAME` varchar(70) DEFAULT NULL,
  `CREATED_BY` varchar(45) NOT NULL,
  `CREATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(45) DEFAULT NULL,
  `MODIFIED_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `user_role` (
  `USER_ROLE_ID` int(10) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(10) NOT NULL,
  `ROLE_ID` int(10) NOT NULL,
  `CREATED_BY` varchar(45) NOT NULL,
  `CREATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(45) DEFAULT NULL,
  `MODIFIED_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`USER_ROLE_ID`),
  KEY `user_role_role_id` (`ROLE_ID`),
  KEY `user_role_user_id` (`USER_ID`),
  CONSTRAINT `user_role_role_id` FOREIGN KEY (`ROLE_ID`) REFERENCES `role` (`role_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `user_role_user_id` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
